# Generated by Django 4.1.2 on 2022-10-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile/<django.db.models.fields.related.OneToOneField>'),
        ),
    ]
