# Generated by Django 4.1.2 on 2022-10-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile/<django.db.models.fields.related.OneToOneField>/'),
        ),
    ]
