# Generated by Django 4.1.2 on 2022-10-10 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(help_text='Enter name of manufacturer', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField(help_text='Enter short product deskription')),
                ('colour', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('firm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.firm')),
                ('type', models.ManyToManyField(help_text="Select type', null=False", to='shop.type')),
            ],
        ),
    ]
