# Generated by Django 4.1.1 on 2022-10-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='product_image'),
        ),
    ]
