# Generated by Django 4.1.2 on 2022-10-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('base', 'base'), ('gel-lack', 'gel-lack'), ('gel', 'gel'), ('top', 'top')], max_length=100, null=True),
        ),
    ]
